### ISSUE TITLE
Fedora 35 image

### ISSUE THREAD

**Issue by ganto** [geerlingguy/docker-fedora34-ansible#1]
[Fedora 35 was released](https://fedoramagazine.org/announcing-fedora-35/) a while ago. Any chance to get a `docker-fedora35-ansible` image? I'm following your example to test Ansible roles and would be in need of a Fedora 35 image. :smiley: 

If not planned would you host it if I would send you an appropriate Dockerfile?

**Comment by stefangweichinger** [comment]
Same here ;-)

**Comment by stefangweichinger** [comment]
It seems to be a one-line patch in `Dockerfile` (and editing `README.md`) in my local tests.

**Comment by geerlingguy** [comment]
You ask, I give: https://github.com/geerlingguy/docker-fedora35-ansible

**Comment by ganto** [comment]
Wow, what a service. Thanks a lot!
